"""Generate BACKLOG.md from a curated taxonomy of real, distinct engineering tasks.

The backlog is data, not prose: every entry names a specific, independently
testable unit of work (a function, class, endpoint, or hardening step) with a
short behavioural spec. Running this script emits well over a thousand concrete
tasks, interleaved across areas so the bot builds breadth rather than sixty
string helpers in a row.

Even this large list is finite, so the runtime also *self-replenishes* the
backlog (see ``builder/backlog_gen.py``); this file is the durable, curated core
that gives the experiment years of high-signal work before it ever has to
improvise.

Usage:
    python tools/gen_backlog.py            # write BACKLOG.md at the repo root
    python tools/gen_backlog.py --count    # just print how many tasks it holds
"""

from __future__ import annotations

import argparse
from pathlib import Path

# --------------------------------------------------------------------------- #
# Foundation: the URL-shortener service and its hardening. Built first, in order,
# because these tasks have real dependencies on one another.
# --------------------------------------------------------------------------- #

FOUNDATION: list[str] = [
    "Reject invalid URLs on POST /links: require an http or https scheme and a host, returning 422 otherwise, with a test for a bad URL.",
    "Add GET /links/{code}/info returning the code, target URL, and creation time as JSON without redirecting.",
    "Add DELETE /links/{code} that removes a link and returns 204, and make GET /{code} return 404 afterwards.",
    "Count redirects: track a hit counter per link and include it in the GET /links/{code}/info response.",
    "Add GET /links returning a JSON list of all links with their codes, targets, and hit counts.",
    "Add pagination to GET /links using limit and offset query parameters with sensible defaults and bounds.",
    "Support a custom alias on POST /links via an optional code field, returning 409 if the alias already exists.",
    "Validate custom aliases: allow only URL-safe characters and a length between 3 and 32, returning 422 otherwise.",
    "Add optional link expiry: accept an expires_in_seconds field and return 410 Gone when an expired link is visited.",
    "Add GET /stats returning totals: number of links, total redirects, and the most-visited code.",
    "Normalise created timestamps to timezone-aware UTC ISO 8601 strings everywhere they appear.",
    "Add GET /healthz/details reporting uptime in seconds and the number of stored links.",
    "Introduce a Storage protocol in app/storage.py so the in-memory store and future backends share one interface.",
    "Add a SQLite-backed store implementing the Storage protocol, selectable by an environment variable, defaulting to in-memory.",
    "Persist hit counts and expiry in the SQLite store so they survive a restart, with a test using a temp database file.",
    "Add a global exception handler returning consistent JSON error bodies with a detail field.",
    "Add basic per-client rate limiting on POST /links using an in-memory token bucket, returning 429 when exceeded.",
    "Add request logging middleware that records method, path, and status without logging request bodies.",
    "Add a configurable maximum URL length and reject overly long targets with 422.",
    "Add an OpenAPI description and example to each endpoint so the generated docs read clearly.",
    "Add a GET / root endpoint returning the service name, version, and a link to /docs.",
    "Add a wire the app.toolkit.strings.slugify helper into a POST /links option that derives a readable alias from a title field.",
]

# --------------------------------------------------------------------------- #
# Toolkit: a self-building standard library. Each tuple is (name, spec) and turns
# into one task that adds the unit to app/toolkit/<module>.py with tests.
# --------------------------------------------------------------------------- #

Item = tuple[str, str]

STRINGS: list[Item] = [
    ("truncate", "shorten a string to a max length, appending an ellipsis only when it was cut"),
    ("word_wrap", "wrap text to a column width without breaking words"),
    ("title_case", "capitalise the first letter of each word, leaving small words like 'of' lowercase unless first"),
    ("snake_case", "convert any string to snake_case"),
    ("camel_case", "convert any string to camelCase"),
    ("pascal_case", "convert any string to PascalCase"),
    ("kebab_case", "convert any string to kebab-case"),
    ("swap_case", "swap the case of every letter"),
    ("strip_ansi", "remove ANSI colour escape sequences from a string"),
    ("strip_html_tags", "remove HTML tags leaving the text content"),
    ("collapse_whitespace", "replace runs of whitespace with a single space and trim"),
    ("remove_accents", "return the ASCII-folded form of an accented string"),
    ("count_words", "count words in a string using unicode-aware splitting"),
    ("count_chars", "return a mapping of character to frequency"),
    ("reverse_words", "reverse the order of words while preserving single spaces"),
    ("is_palindrome", "check whether a string is a palindrome ignoring case and non-letters"),
    ("common_prefix", "return the longest common prefix of a list of strings"),
    ("common_suffix", "return the longest common suffix of a list of strings"),
    ("levenshtein", "compute the Levenshtein edit distance between two strings"),
    ("hamming_distance", "compute the Hamming distance between two equal-length strings"),
    ("jaccard_similarity", "compute the Jaccard similarity of the character sets of two strings"),
    ("pluralize", "return the naive English plural of a noun"),
    ("singularize", "return the naive English singular of a noun"),
    ("ordinal", "return the ordinal string for an integer such as 1st, 2nd, 3rd"),
    ("ordinalize", "return an integer with its ordinal suffix as a string"),
    ("indent", "indent every line of a string by a given number of spaces"),
    ("dedent", "remove common leading whitespace from every line"),
    ("center_pad", "centre a string within a width using a fill character"),
    ("mask", "mask all but the last n characters of a string with a fill character"),
    ("initials", "return the uppercase initials of a full name"),
    ("shorten_middle", "shorten a string keeping both ends and eliding the middle"),
    ("count_occurrences", "count non-overlapping occurrences of a substring"),
    ("replace_nth", "replace only the nth occurrence of a substring"),
    ("lines", "split text into lines handling all common newline conventions"),
    ("unindent_block", "strip a fixed prefix from each line if present"),
    ("expand_tabs", "expand tab characters to spaces using a tab size"),
    ("is_blank", "return whether a string is empty or only whitespace"),
    ("ensure_prefix", "prepend a prefix only if the string does not already start with it"),
    ("ensure_suffix", "append a suffix only if the string does not already end with it"),
    ("strip_prefix", "remove a prefix if present, otherwise return the string unchanged"),
    ("strip_suffix", "remove a suffix if present, otherwise return the string unchanged"),
    ("squeeze", "collapse consecutive repeated characters into one"),
    ("rot13", "apply the ROT13 substitution cipher"),
    ("caesar_cipher", "shift letters by a given amount wrapping within the alphabet"),
    ("to_charset", "return the sorted set of distinct characters in a string"),
    ("longest_common_substring", "return the longest substring shared by two strings"),
]

NUMBERS: list[Item] = [
    ("clamp", "constrain a number to an inclusive min and max"),
    ("lerp", "linearly interpolate between two numbers by a fraction"),
    ("inverse_lerp", "return the fraction of a value between two bounds"),
    ("remap", "map a value from one numeric range to another"),
    ("round_to", "round a number to the nearest multiple of a step"),
    ("round_half_up", "round half away from zero rather than banker's rounding"),
    ("sign", "return -1, 0, or 1 for the sign of a number"),
    ("is_close", "compare two floats within a relative and absolute tolerance"),
    ("gcd", "return the greatest common divisor of two integers"),
    ("lcm", "return the least common multiple of two integers"),
    ("factorial", "return n! for a non-negative integer"),
    ("is_prime", "test whether an integer is prime"),
    ("primes_up_to", "return all primes up to n using a sieve"),
    ("prime_factors", "return the prime factorisation of an integer"),
    ("divisors", "return all positive divisors of an integer"),
    ("fibonacci", "return the nth Fibonacci number"),
    ("digits", "return the decimal digits of an integer as a list"),
    ("digit_sum", "return the sum of the decimal digits of an integer"),
    ("digital_root", "return the repeated digit sum of an integer"),
    ("to_base", "convert a non-negative integer to a string in a given base"),
    ("from_base", "parse an integer from a string in a given base"),
    ("roman_to_int", "convert a Roman numeral to an integer"),
    ("int_to_roman", "convert an integer to a Roman numeral"),
    ("ncr", "return the binomial coefficient n choose r"),
    ("npr", "return the number of permutations of n taken r at a time"),
    ("is_power_of_two", "test whether an integer is a power of two"),
    ("next_power_of_two", "return the smallest power of two at least n"),
    ("bit_count", "count the set bits in a non-negative integer"),
    ("rotate_bits", "rotate the bits of a fixed-width integer left or right"),
    ("mean", "return the arithmetic mean of a sequence of numbers"),
    ("median", "return the median of a sequence of numbers"),
    ("mode", "return the most common value in a sequence"),
    ("variance", "return the sample variance of a sequence"),
    ("stddev", "return the sample standard deviation of a sequence"),
    ("percentile", "return the given percentile of a sequence using linear interpolation"),
    ("normalize_vector", "scale a list of numbers so they sum to one"),
    ("cumulative_sum", "return the running cumulative sums of a sequence"),
    ("moving_average", "return the simple moving average over a window"),
    ("clamp_index", "clamp an index into the valid range for a length"),
    ("safe_divide", "divide two numbers returning a default when the divisor is zero"),
]

DATETIME: list[Item] = [
    ("parse_iso", "parse an ISO 8601 string into a timezone-aware datetime"),
    ("to_iso", "format a datetime as an ISO 8601 string in UTC"),
    ("now_utc", "return the current timezone-aware UTC datetime"),
    ("humanize_delta", "describe a timedelta in words like '3 hours ago'"),
    ("days_between", "return the whole number of days between two dates"),
    ("business_days_between", "count weekdays between two dates"),
    ("add_business_days", "add a number of weekdays to a date"),
    ("is_weekend", "return whether a date falls on a Saturday or Sunday"),
    ("start_of_day", "return the datetime at midnight for a given datetime"),
    ("end_of_day", "return the last microsecond of the day for a datetime"),
    ("start_of_week", "return the date of the Monday of a date's week"),
    ("start_of_month", "return the first day of a date's month"),
    ("end_of_month", "return the last day of a date's month"),
    ("days_in_month", "return how many days are in a given year and month"),
    ("is_leap_year", "return whether a year is a leap year"),
    ("day_of_year", "return the 1-based day of the year for a date"),
    ("week_of_year", "return the ISO week number for a date"),
    ("quarter_of", "return the calendar quarter 1-4 for a date"),
    ("age_in_years", "return a whole-year age from a birth date to a reference date"),
    ("round_datetime", "round a datetime to the nearest interval such as 15 minutes"),
    ("floor_datetime", "floor a datetime to an interval"),
    ("ceil_datetime", "ceil a datetime to an interval"),
    ("parse_duration", "parse strings like '1h30m' into a timedelta"),
    ("format_duration", "format a timedelta as a compact string like '1h30m'"),
    ("iter_dates", "yield each date in an inclusive range"),
    ("next_weekday", "return the next date matching a given weekday"),
    ("timestamp_ms", "return the current unix time in milliseconds"),
    ("from_timestamp_ms", "build a UTC datetime from unix milliseconds"),
    ("timezone_convert", "convert a datetime between two named timezones"),
    ("overlaps", "return whether two datetime intervals overlap"),
]

COLLECTIONS: list[Item] = [
    ("chunk", "split an iterable into lists of a fixed size"),
    ("flatten", "flatten one level of nested iterables"),
    ("flatten_deep", "recursively flatten arbitrarily nested iterables"),
    ("unique", "return items in order with duplicates removed"),
    ("unique_by", "deduplicate items by a key function preserving order"),
    ("group_by", "group items into a dict of lists by a key function"),
    ("partition", "split items into two lists by a predicate"),
    ("count_by", "return a Counter of items keyed by a function"),
    ("index_by", "build a dict keyed by a function, last value winning"),
    ("windowed", "yield overlapping windows of a given size"),
    ("pairwise", "yield consecutive overlapping pairs"),
    ("take", "return the first n items of an iterable"),
    ("drop", "skip the first n items of an iterable"),
    ("take_while", "yield items while a predicate holds"),
    ("drop_while", "skip items while a predicate holds then yield the rest"),
    ("first", "return the first item matching a predicate or a default"),
    ("last", "return the last item of an iterable or a default"),
    ("nth", "return the nth item of an iterable or a default"),
    ("find_index", "return the index of the first item matching a predicate"),
    ("compact", "remove falsy values from an iterable"),
    ("intersperse", "insert a separator value between items"),
    ("flatten_dict", "flatten a nested dict into dotted keys"),
    ("unflatten_dict", "rebuild a nested dict from dotted keys"),
    ("deep_merge", "recursively merge two dicts"),
    ("pick", "return a dict with only the given keys"),
    ("omit", "return a dict without the given keys"),
    ("invert_dict", "swap keys and values of a dict"),
    ("map_keys", "apply a function to every key of a dict"),
    ("map_values", "apply a function to every value of a dict"),
    ("zip_dict", "build a dict from parallel key and value iterables"),
    ("rotate", "rotate a list by n positions"),
    ("chunk_evenly", "split a list into n groups of nearly equal size"),
    ("frequencies", "return a dict of value to count"),
    ("most_common", "return the n most common items with counts"),
    ("difference", "return items in the first iterable not in the second"),
    ("intersection", "return items present in all given iterables preserving order"),
    ("symmetric_difference", "return items in exactly one of two iterables"),
    ("cartesian_product", "return the cartesian product of several iterables"),
    ("transpose", "transpose a list of equal-length rows"),
    ("scan", "return successive reduced values from the left"),
    ("dedupe_adjacent", "remove consecutive duplicate items"),
    ("chunk_by", "split a sequence into runs where a key function is constant"),
    ("sliding_max", "return the maximum of each sliding window"),
    ("argmin", "return the index of the smallest item by a key"),
    ("argmax", "return the index of the largest item by a key"),
]

FUNCTIONAL: list[Item] = [
    ("compose", "compose functions right to left"),
    ("pipe", "compose functions left to right"),
    ("curry", "return a curried version of a function"),
    ("partial_right", "bind arguments from the right of a function"),
    ("memoize", "cache a function's results by its arguments"),
    ("once", "wrap a function so it runs at most once, caching the result"),
    ("debounce", "return a function that delays calls until quiet for an interval"),
    ("throttle", "return a function that runs at most once per interval"),
    ("negate", "return a predicate that inverts another predicate"),
    ("constant", "return a function that always returns a fixed value"),
    ("identity", "return its argument unchanged"),
    ("tap", "call a side-effecting function and return the original value"),
    ("retry_call", "call a function retrying on exception with a max attempt count"),
    ("safe_call", "call a function returning a default on any exception"),
    ("apply_n", "apply a function to a value n times"),
    ("flip", "return a binary function with its arguments swapped"),
    ("all_pass", "combine predicates into one that requires all to pass"),
    ("any_pass", "combine predicates into one that requires any to pass"),
    ("juxt", "apply several functions to the same arguments returning a tuple"),
    ("complement", "return a function returning the boolean negation of another"),
]

ENCODING: list[Item] = [
    ("base62_encode", "encode a non-negative integer to a base62 string"),
    ("base62_decode", "decode a base62 string to an integer"),
    ("base58_encode", "encode bytes to a Bitcoin-style base58 string"),
    ("base58_decode", "decode a base58 string to bytes"),
    ("base32_encode", "encode bytes to base32"),
    ("base32_decode", "decode a base32 string to bytes"),
    ("hex_encode", "encode bytes to a lowercase hex string"),
    ("hex_decode", "decode a hex string to bytes"),
    ("url_encode", "percent-encode a string for use in a URL"),
    ("url_decode", "decode a percent-encoded string"),
    ("base64url_encode", "encode bytes to URL-safe base64 without padding"),
    ("base64url_decode", "decode URL-safe base64"),
    ("to_query_string", "encode a mapping as a URL query string"),
    ("parse_query_string", "parse a URL query string into a dict of lists"),
    ("html_escape", "escape the five special HTML characters"),
    ("html_unescape", "unescape HTML entities"),
    ("json_minify", "remove insignificant whitespace from a JSON string"),
    ("zigzag_encode", "map signed integers to unsigned with zigzag encoding"),
    ("zigzag_decode", "reverse zigzag encoding"),
    ("varint_encode", "encode an integer as LEB128 varint bytes"),
    ("varint_decode", "decode a LEB128 varint from bytes"),
    ("morse_encode", "encode ASCII letters and digits to Morse code"),
    ("morse_decode", "decode Morse code to text"),
    ("percent_encode_bytes", "percent-encode raw bytes"),
    ("punycode_encode", "encode a unicode host label to punycode"),
]

HASHING: list[Item] = [
    ("md5_hex", "return the md5 hex digest of bytes"),
    ("sha256_hex", "return the sha256 hex digest of bytes"),
    ("sha1_hex", "return the sha1 hex digest of bytes"),
    ("crc32", "return the crc32 checksum of bytes"),
    ("adler32", "return the adler32 checksum of bytes"),
    ("fnv1a_32", "compute the 32-bit FNV-1a hash of bytes"),
    ("djb2", "compute the djb2 hash of a string"),
    ("murmur3_32", "compute the 32-bit MurmurHash3 of bytes"),
    ("hmac_sha256", "compute an HMAC-SHA256 hex digest for a key and message"),
    ("stable_hash", "return a deterministic hash of a JSON-serialisable value"),
    ("checksum_file", "return the sha256 of a file read in chunks"),
    ("short_hash", "return a short base62 hash of a string for cache keys"),
    ("luhn_checksum", "compute the Luhn check digit for a numeric string"),
    ("verify_luhn", "validate a number string against its Luhn check digit"),
    ("simhash", "compute a 64-bit simhash of a token list for near-duplicate detection"),
]

VALIDATION: list[Item] = [
    ("is_email", "validate an email address with a pragmatic regex"),
    ("is_url", "validate an http or https URL"),
    ("is_ipv4", "validate an IPv4 address"),
    ("is_ipv6", "validate an IPv6 address"),
    ("is_uuid", "validate a UUID string"),
    ("is_hex_color", "validate a 3- or 6-digit hex colour"),
    ("is_slug", "validate a lowercase hyphenated slug"),
    ("is_credit_card", "validate a credit card number via the Luhn algorithm"),
    ("is_isbn10", "validate an ISBN-10 including its check digit"),
    ("is_isbn13", "validate an ISBN-13 including its check digit"),
    ("is_mac_address", "validate a MAC address in colon or hyphen form"),
    ("is_semver", "validate a semantic version string"),
    ("is_json", "return whether a string parses as JSON"),
    ("is_port", "validate that an integer is a usable TCP port"),
    ("is_latitude", "validate a latitude between -90 and 90"),
    ("is_longitude", "validate a longitude between -180 and 180"),
    ("is_hostname", "validate an RFC-compliant hostname"),
    ("is_strong_password", "check a password against length and character-class rules"),
    ("is_ascii", "return whether a string is pure ASCII"),
    ("is_iban", "validate an IBAN with its mod-97 checksum"),
    ("password_strength", "score a password from 0 to 4 with reasons"),
    ("is_e164_phone", "validate a phone number in E.164 form"),
]

PARSING: list[Item] = [
    ("parse_semver", "parse a semantic version into major, minor, patch, and pre-release"),
    ("compare_semver", "compare two semantic versions returning -1, 0, or 1"),
    ("parse_bool", "parse strings like yes/no/on/off/1/0 into a bool"),
    ("parse_bytes_size", "parse '10MB' style sizes into a byte count"),
    ("format_bytes_size", "format a byte count as a human-readable size"),
    ("parse_key_value", "parse 'k=v,k2=v2' strings into a dict"),
    ("parse_cookie", "parse an HTTP Cookie header into a dict"),
    ("parse_accept_language", "parse an Accept-Language header into weighted tags"),
    ("parse_range_header", "parse an HTTP Range header into byte ranges"),
    ("parse_data_uri", "parse a data: URI into its media type and bytes"),
    ("parse_content_type", "split a Content-Type header into type and parameters"),
    ("parse_csv_line", "parse a single CSV line honouring quotes"),
    ("parse_ini", "parse a simple INI string into a nested dict"),
    ("parse_env_file", "parse a .env file into a dict ignoring comments"),
    ("parse_frontmatter", "split YAML-ish front matter from markdown body"),
    ("parse_cron", "parse a five-field cron expression into its component sets"),
    ("cron_matches", "return whether a datetime satisfies a parsed cron expression"),
    ("parse_duration_iso", "parse an ISO 8601 duration into a timedelta"),
    ("parse_url", "split a URL into scheme, host, port, path, query, and fragment"),
    ("build_url", "assemble a URL from its component parts"),
    ("parse_user_agent", "extract a coarse browser and OS from a User-Agent string"),
    ("tokenize_words", "split text into word tokens with unicode awareness"),
    ("parse_hex_color", "parse a hex colour into an r,g,b tuple"),
    ("parse_query_params_typed", "parse query params coercing ints, floats, and bools"),
]

DATASTRUCTURES: list[Item] = [
    ("LRUCache", "a fixed-capacity least-recently-used cache with get and put"),
    ("LFUCache", "a least-frequently-used cache with eviction"),
    ("TTLCache", "a cache whose entries expire after a time to live"),
    ("Trie", "a prefix tree supporting insert, search, and prefix queries"),
    ("BloomFilter", "a bloom filter with add and probable-membership queries"),
    ("RingBuffer", "a fixed-size circular buffer overwriting oldest items"),
    ("PriorityQueue", "a binary-heap priority queue with push and pop"),
    ("UnionFind", "a disjoint-set structure with union and find and path compression"),
    ("Stack", "a simple stack with push, pop, and peek"),
    ("Queue", "a FIFO queue backed by a deque"),
    ("Deque", "a double-ended queue wrapper with a friendly API"),
    ("CountMinSketch", "a probabilistic frequency estimator"),
    ("SkipList", "an ordered skip list with insert and search"),
    ("SortedList", "a list kept sorted with bisect-based insert and lookup"),
    ("MultiSet", "a bag counting element multiplicities"),
    ("BiMap", "a bidirectional map with forward and inverse lookup"),
    ("DefaultDict", "a dict subclass creating missing values from a factory"),
    ("FrozenDict", "an immutable, hashable mapping"),
    ("IntervalTree", "store intervals and query those overlapping a point"),
    ("Graph", "an adjacency-list graph with add_edge and neighbours"),
    ("DirectedGraph", "a directed graph supporting in and out degree queries"),
    ("FenwickTree", "a binary indexed tree for prefix sums and point updates"),
    ("SegmentTree", "a segment tree for range-sum queries and point updates"),
    ("CircularCounter", "a rolling window counter over recent events"),
    ("ObjectPool", "a reusable-object pool with acquire and release"),
]

ALGORITHMS: list[Item] = [
    ("binary_search", "return the index of a target in a sorted list or -1"),
    ("bisect_left", "return the leftmost insertion point in a sorted list"),
    ("quicksort", "sort a list with an in-place quicksort"),
    ("mergesort", "sort a list with a stable merge sort"),
    ("heapsort", "sort a list using a binary heap"),
    ("insertion_sort", "sort a small list with insertion sort"),
    ("counting_sort", "sort non-negative integers with counting sort"),
    ("kth_smallest", "return the kth smallest element using quickselect"),
    ("two_sum", "return indices of two numbers summing to a target"),
    ("three_sum", "return unique triples summing to zero"),
    ("max_subarray_sum", "return the maximum contiguous subarray sum via Kadane"),
    ("longest_increasing_subsequence", "return the length of the longest increasing subsequence"),
    ("edit_distance", "return the Levenshtein distance via dynamic programming"),
    ("longest_common_subsequence", "return the LCS length of two sequences"),
    ("knapsack_01", "solve the 0/1 knapsack problem for weights and values"),
    ("coin_change", "return the fewest coins making an amount or -1"),
    ("bfs_shortest_path", "return the shortest unweighted path in a graph"),
    ("dfs_order", "return the depth-first visitation order from a node"),
    ("dijkstra", "return shortest distances from a source in a weighted graph"),
    ("topological_sort", "return a topological ordering of a DAG or raise on a cycle"),
    ("has_cycle", "detect whether a directed graph contains a cycle"),
    ("connected_components", "return the connected components of an undirected graph"),
    ("kmp_search", "find a pattern in text using the KMP algorithm"),
    ("rabin_karp_search", "find a pattern in text using rolling hashes"),
    ("boyer_moore_search", "find a pattern using the Boyer-Moore bad-character rule"),
    ("run_length_encode", "run-length encode a sequence"),
    ("run_length_decode", "decode a run-length encoded sequence"),
    ("huffman_encode", "build Huffman codes for a symbol frequency table"),
    ("permutations_of", "yield all permutations of a sequence"),
    ("combinations_of", "yield all combinations of a given size"),
    ("power_set", "yield all subsets of a set"),
    ("next_permutation", "transform a list into its next lexicographic permutation"),
    ("reservoir_sample", "sample k items uniformly from a stream of unknown length"),
    ("shuffle_seeded", "return a deterministically shuffled copy given a seed"),
    ("merge_intervals", "merge a list of overlapping intervals"),
    ("insert_interval", "insert an interval into a sorted non-overlapping list"),
]

RANDOMNESS: list[Item] = [
    ("random_string", "generate a random alphanumeric string of a given length"),
    ("random_hex", "generate a random hex token of a given byte length"),
    ("uuid4", "return a random UUID4 string"),
    ("uuid7", "return a time-ordered UUID7 string"),
    ("nanoid", "generate a URL-safe NanoID of a given size"),
    ("random_choice_weighted", "choose an item given per-item weights"),
    ("random_sample_without_replacement", "sample k distinct items from a population"),
    ("dice_roll", "roll dice from notation like 3d6+2"),
    ("random_color_hex", "generate a random hex colour"),
    ("random_password", "generate a password meeting configurable class rules"),
    ("shuffled", "return a shuffled copy of a sequence"),
    ("random_bytes", "return n cryptographically strong random bytes"),
    ("random_bool", "return True with a given probability"),
    ("gaussian", "sample from a normal distribution with a mean and sigma"),
    ("random_pin", "generate a numeric PIN of a given length"),
]

TEXTSEARCH: list[Item] = [
    ("fuzzy_ratio", "return a 0-100 similarity ratio between two strings"),
    ("fuzzy_best_match", "return the best matching candidate for a query"),
    ("ngrams", "return the character n-grams of a string"),
    ("word_ngrams", "return the word n-grams of a token list"),
    ("soundex", "return the Soundex code of a word"),
    ("metaphone", "return the Metaphone code of a word"),
    ("highlight", "wrap matches of a query in a string with markers"),
    ("tokenize_sentences", "split text into sentences with a simple heuristic"),
    ("keyword_density", "return the frequency ratio of each word in text"),
    ("longest_word", "return the longest word in a string"),
    ("autocomplete", "return candidates that start with a prefix, ranked"),
    ("did_you_mean", "suggest the closest term from a dictionary"),
    ("jaro_winkler", "compute the Jaro-Winkler similarity of two strings"),
    ("dice_coefficient", "compute the Sorensen-Dice coefficient of two strings"),
    ("tf", "compute term frequencies for a document"),
]

FILES: list[Item] = [
    ("human_path", "shorten a filesystem path with a home tilde and ellipsis"),
    ("split_extension", "split a filename into stem and extension"),
    ("change_extension", "replace a filename's extension"),
    ("sanitize_filename", "replace characters unsafe for filenames"),
    ("unique_filename", "append a counter to avoid an existing filename"),
    ("guess_mime_type", "guess a MIME type from a filename extension"),
    ("read_lines", "read a text file into a list of stripped lines"),
    ("atomic_write", "write text to a file atomically via a temp file and rename"),
    ("ensure_dir", "create a directory and its parents if missing"),
    ("dir_size", "return the total size in bytes of a directory tree"),
    ("walk_files", "yield file paths under a directory matching a glob"),
    ("is_binary_file", "guess whether a file is binary by sampling bytes"),
    ("tail_lines", "return the last n lines of a text file efficiently"),
    ("format_file_size", "format a byte count using binary units"),
    ("relative_to", "return a path relative to a base, falling back to absolute"),
    ("copy_tree_filtered", "copy a directory tree excluding a set of glob patterns"),
    ("checksum_dir", "return a combined checksum of a directory's files"),
    ("path_depth", "return the number of path segments in a path"),
    ("common_base", "return the deepest common directory of several paths"),
    ("temp_path", "return a unique path inside the system temp directory"),
]

NET: list[Item] = [
    ("build_query", "build a query string from a dict, skipping None values"),
    ("join_url", "join a base URL with a relative path safely"),
    ("strip_query", "return a URL with its query string removed"),
    ("get_query_param", "return the first value of a query parameter from a URL"),
    ("set_query_param", "return a URL with a query parameter set or replaced"),
    ("remove_query_param", "return a URL with a query parameter removed"),
    ("domain_of", "return the registered domain of a URL"),
    ("subdomain_of", "return the subdomain portion of a host"),
    ("is_same_origin", "return whether two URLs share scheme, host, and port"),
    ("normalize_url", "canonicalise a URL by lowercasing host and sorting query params"),
    ("idna_encode", "encode a unicode host to its ASCII IDNA form"),
    ("ip_to_int", "convert an IPv4 address to its integer form"),
    ("int_to_ip", "convert an integer to an IPv4 address"),
    ("cidr_contains", "return whether a CIDR block contains an address"),
    ("cidr_hosts", "yield the usable host addresses of a CIDR block"),
    ("parse_authority", "split a userinfo@host:port authority into parts"),
    ("is_private_ip", "return whether an IPv4 address is in a private range"),
    ("mask_ip", "mask the final octet of an IPv4 address"),
    ("gravatar_url", "build a Gravatar image URL from an email"),
    ("mailto_link", "build a mailto: link with subject and body parameters"),
]

COLORS: list[Item] = [
    ("hex_to_rgb", "convert a hex colour to an r,g,b tuple"),
    ("rgb_to_hex", "convert an r,g,b tuple to a hex colour"),
    ("rgb_to_hsl", "convert RGB to HSL"),
    ("hsl_to_rgb", "convert HSL to RGB"),
    ("rgb_to_hsv", "convert RGB to HSV"),
    ("hsv_to_rgb", "convert HSV to RGB"),
    ("lighten", "lighten a colour by a percentage"),
    ("darken", "darken a colour by a percentage"),
    ("mix_colors", "blend two colours by a ratio"),
    ("contrast_ratio", "compute the WCAG contrast ratio of two colours"),
    ("readable_text_color", "choose black or white text for a background colour"),
    ("relative_luminance", "compute the relative luminance of a colour"),
    ("complementary", "return the complementary colour of a colour"),
    ("grayscale", "convert a colour to its grayscale equivalent"),
    ("random_pastel", "generate a random pastel colour"),
]

UNITS: list[Item] = [
    ("celsius_to_fahrenheit", "convert Celsius to Fahrenheit"),
    ("fahrenheit_to_celsius", "convert Fahrenheit to Celsius"),
    ("celsius_to_kelvin", "convert Celsius to Kelvin"),
    ("km_to_miles", "convert kilometres to miles"),
    ("miles_to_km", "convert miles to kilometres"),
    ("meters_to_feet", "convert metres to feet"),
    ("kg_to_pounds", "convert kilograms to pounds"),
    ("pounds_to_kg", "convert pounds to kilograms"),
    ("liters_to_gallons", "convert litres to US gallons"),
    ("bytes_to_human", "convert a byte count to a human string"),
    ("mps_to_kmh", "convert metres per second to kilometres per hour"),
    ("radians_to_degrees", "convert radians to degrees"),
    ("degrees_to_radians", "convert degrees to radians"),
    ("acres_to_hectares", "convert acres to hectares"),
    ("knots_to_kmh", "convert knots to kilometres per hour"),
    ("bpm_to_hz", "convert beats per minute to hertz"),
    ("pt_to_px", "convert typographic points to pixels at 96 dpi"),
    ("cups_to_ml", "convert US cups to millilitres"),
    ("mph_to_kmh", "convert miles per hour to kilometres per hour"),
    ("joules_to_calories", "convert joules to calories"),
]

GEOMETRY: list[Item] = [
    ("distance_2d", "return the Euclidean distance between two points"),
    ("manhattan_distance", "return the Manhattan distance between two points"),
    ("haversine", "return the great-circle distance between two lat/long points"),
    ("point_in_rect", "return whether a point lies inside a rectangle"),
    ("point_in_polygon", "return whether a point lies inside a polygon"),
    ("polygon_area", "return the area of a simple polygon via the shoelace formula"),
    ("polygon_perimeter", "return the perimeter of a polygon"),
    ("rect_intersection", "return the intersection of two rectangles or None"),
    ("rect_union", "return the bounding rectangle of two rectangles"),
    ("bounding_box", "return the bounding box of a set of points"),
    ("centroid", "return the centroid of a set of points"),
    ("rotate_point", "rotate a point around an origin by an angle"),
    ("scale_point", "scale a point about an origin"),
    ("line_intersection", "return the intersection point of two line segments or None"),
    ("convex_hull", "return the convex hull of a set of points"),
]

FINANCE: list[Item] = [
    ("compound_interest", "compute the future value with compound interest"),
    ("simple_interest", "compute simple interest over a period"),
    ("monthly_payment", "compute a fixed loan payment given rate and term"),
    ("amortization_schedule", "return the per-period amortisation rows of a loan"),
    ("future_value_annuity", "compute the future value of a regular annuity"),
    ("present_value", "discount a future amount to present value"),
    ("npv", "compute the net present value of cash flows"),
    ("irr", "estimate the internal rate of return of cash flows"),
    ("percentage_change", "compute the percentage change between two values"),
    ("apply_discount", "apply a percentage discount to a price"),
    ("split_bill", "split an amount with tip evenly across people"),
    ("round_currency", "round an amount to two decimal places using half-up"),
    ("format_currency", "format an amount with a currency symbol and grouping"),
    ("vat_add", "add a VAT percentage to a net amount"),
    ("vat_extract", "extract the VAT portion from a gross amount"),
]

CONFIG: list[Item] = [
    ("get_env_bool", "read a boolean environment variable with a default"),
    ("get_env_int", "read an integer environment variable with a default"),
    ("get_env_list", "read a comma-separated environment variable into a list"),
    ("deep_get", "read a nested dict value by a dotted path with a default"),
    ("deep_set", "set a nested dict value by a dotted path creating parents"),
    ("merge_configs", "merge a list of config dicts with later ones winning"),
    ("expand_env_vars", "expand ${VAR} references in config strings"),
    ("mask_secrets", "redact values of keys that look like secrets in a dict"),
    ("validate_schema", "validate a dict against a simple type schema"),
    ("apply_defaults", "fill missing keys in a dict from a defaults dict"),
    ("flatten_config", "flatten a nested config to dotted keys for env export"),
    ("coerce_types", "coerce string config values to declared types"),
    ("freeze_config", "return an immutable view of a config dict"),
    ("diff_configs", "return the added, removed, and changed keys between two configs"),
    ("load_layered", "merge defaults, file, and environment config layers"),
]

RESILIENCE: list[Item] = [
    ("retry", "a decorator retrying on exception with configurable attempts"),
    ("exponential_backoff", "yield increasing delays with optional jitter"),
    ("CircuitBreaker", "a circuit breaker that opens after repeated failures"),
    ("TokenBucket", "a token-bucket rate limiter with try_acquire"),
    ("LeakyBucket", "a leaky-bucket rate limiter"),
    ("timeout_call", "run a callable raising if it exceeds a deadline"),
    ("with_fallback", "call a primary function falling back to a secondary on error"),
    ("rate_limited", "a decorator enforcing a maximum call rate"),
    ("bulkhead", "limit the number of concurrent calls to a function"),
    ("Deadline", "track a wall-clock deadline with remaining and expired"),
    ("jittered_delay", "return a randomised delay around a base"),
    ("RetryBudget", "cap the fraction of calls that may be retried"),
]

CLI: list[Item] = [
    ("parse_args_simple", "parse a list of --key value CLI args into a dict"),
    ("confirm_prompt", "return a yes/no decision from a prompt with a default"),
    ("progress_bar", "render a text progress bar for a fraction"),
    ("spinner_frames", "yield spinner animation frames"),
    ("colorize", "wrap text in ANSI colour codes by name"),
    ("table", "render a list of rows as an aligned text table"),
    ("wrap_columns", "lay out items into aligned columns for a terminal width"),
    ("format_help", "format a command's options into a help block"),
    ("prompt_choice", "prompt the user to pick from a numbered list"),
    ("elapsed_timer", "return a context manager reporting elapsed time"),
    ("bytes_progress", "format a downloaded/total bytes progress string"),
    ("strip_ansi_width", "measure the display width of a string ignoring ANSI codes"),
    ("box", "draw a text box around a block of lines"),
    ("tree_view", "render a nested mapping as an indented tree"),
    ("countdown", "yield a countdown of remaining seconds"),
]

WEBFRAMEWORK: list[Item] = [
    ("Router", "a minimal path router matching methods and patterns to handlers"),
    ("path_to_regex", "compile a path pattern like /users/{id} to a regex"),
    ("match_route", "match a method and path against a route table"),
    ("parse_headers", "parse a raw HTTP header block into a case-insensitive dict"),
    ("build_response", "build a raw HTTP response from status, headers, and body"),
    ("parse_request_line", "parse an HTTP request line into method, path, and version"),
    ("query_middleware", "middleware that parses the query string onto the request"),
    ("cors_headers", "build CORS response headers for an origin policy"),
    ("etag_for", "compute a strong ETag for a response body"),
    ("content_negotiation", "pick a response type from an Accept header and offers"),
    ("cookie_header", "build a Set-Cookie header with common attributes"),
    ("parse_multipart_boundary", "extract the boundary from a multipart content type"),
    ("status_text", "return the reason phrase for an HTTP status code"),
    ("range_response", "compute the byte slice and headers for a Range request"),
    ("redirect_response", "build a redirect response to a location"),
]

OBSERVABILITY: list[Item] = [
    ("Stopwatch", "a start/stop stopwatch reporting elapsed seconds"),
    ("Timer", "a context manager measuring a block's duration"),
    ("RateCounter", "count events and report a per-second rate"),
    ("Histogram", "record values and report bucketed counts and quantiles"),
    ("moving_percentile", "maintain an approximate percentile over a stream"),
    ("log_context", "a context manager attaching key/values to log records"),
    ("redact_pii", "redact emails and phone numbers from a log string"),
    ("format_log_line", "format a structured log record as a single line"),
    ("counter_registry", "a registry of named counters with increment and snapshot"),
    ("gauge_registry", "a registry of named gauges with set and snapshot"),
    ("sample_rate", "decide whether to sample an event at a given rate"),
    ("span_id", "generate a random span id for tracing"),
    ("elapsed_ms", "return milliseconds elapsed since a start time"),
    ("throughput", "compute items-per-second given a count and duration"),
    ("format_metrics", "render a metrics snapshot in a Prometheus-like text format"),
]

SERIALIZATION: list[Item] = [
    ("to_jsonl", "serialise an iterable of objects to JSON Lines text"),
    ("from_jsonl", "parse JSON Lines text into a list of objects"),
    ("dataclass_to_dict", "recursively convert a dataclass instance to a dict"),
    ("dict_to_dataclass", "build a dataclass instance from a dict"),
    ("csv_to_dicts", "parse CSV text into a list of row dicts"),
    ("dicts_to_csv", "serialise a list of dicts to CSV text"),
    ("stable_json", "serialise a value to JSON with sorted keys for stable output"),
    ("json_pointer_get", "resolve an RFC 6901 JSON pointer against a document"),
    ("merge_patch", "apply an RFC 7386 JSON merge patch to a document"),
    ("flatten_json", "flatten nested JSON to path/value pairs"),
    ("pretty_bytes", "hexdump bytes into an offset/hex/ascii listing"),
    ("encode_msgpack_int", "encode a small integer in a msgpack-like format"),
    ("to_query_object", "serialise a nested object to bracketed query parameters"),
    ("xml_escape", "escape text for safe inclusion in XML"),
    ("to_toml_scalar", "render a Python scalar as a TOML value"),
]

SECURITY: list[Item] = [
    ("constant_time_equals", "compare two strings in constant time"),
    ("generate_token", "generate a URL-safe secret token of a byte length"),
    ("hash_password", "hash a password with a salted PBKDF2 and return an encoded string"),
    ("verify_password", "verify a password against a PBKDF2 encoded hash"),
    ("totp_now", "compute the current TOTP code for a base32 secret"),
    ("verify_totp", "verify a TOTP code allowing a small time window"),
    ("hotp", "compute an HOTP code for a secret and counter"),
    ("sign_value", "sign a string with an HMAC and append the signature"),
    ("unsign_value", "verify and strip an HMAC signature from a signed string"),
    ("mask_email", "mask the local part of an email for display"),
    ("mask_card", "mask all but the last four digits of a card number"),
    ("random_salt", "generate a random salt of a byte length"),
    ("timing_safe_token", "generate and compare tokens without timing leaks"),
    ("password_entropy_bits", "estimate the entropy in bits of a password"),
    ("redact_secrets_in_url", "redact credentials embedded in a URL"),
]

BITS: list[Item] = [
    ("set_bit", "return an integer with the bit at a position set"),
    ("clear_bit", "return an integer with the bit at a position cleared"),
    ("toggle_bit", "return an integer with the bit at a position toggled"),
    ("test_bit", "return whether the bit at a position is set"),
    ("lowest_set_bit", "return the index of the lowest set bit or -1"),
    ("highest_set_bit", "return the index of the highest set bit or -1"),
    ("count_leading_zeros", "count leading zero bits in a fixed-width integer"),
    ("count_trailing_zeros", "count trailing zero bits of an integer"),
    ("reverse_bits", "reverse the bits of a fixed-width integer"),
    ("parity", "return the parity bit of an integer"),
    ("bit_length", "return the number of bits needed to represent an integer"),
    ("bitmask", "build a mask with the lowest n bits set"),
    ("extract_bits", "extract a bit field from an integer given offset and width"),
    ("pack_bits", "pack a list of booleans into an integer"),
    ("unpack_bits", "unpack an integer into a list of booleans of a width"),
    ("gray_encode", "convert a binary integer to Gray code"),
    ("gray_decode", "convert a Gray-coded integer back to binary"),
    ("swap_nibbles", "swap the two nibbles of a byte"),
    ("rotate_left", "rotate a fixed-width integer left by n bits"),
    ("rotate_right", "rotate a fixed-width integer right by n bits"),
    ("interleave_bits", "interleave the bits of two integers into a Morton code"),
    ("deinterleave_bits", "split a Morton code back into two integers"),
    ("hamming_weight", "return the number of set bits in an integer"),
    ("bits_to_bytes", "pack a bit list into a bytes object"),
]

STREAMS: list[Item] = [
    ("batched", "yield tuples of up to n items from an iterable"),
    ("iterate", "yield x, f(x), f(f(x)) and so on lazily"),
    ("repeat_each", "repeat each item of an iterable n times"),
    ("cycle_n", "cycle an iterable a fixed number of times"),
    ("interleave_streams", "round-robin interleave several iterables"),
    ("chain_lazy", "lazily chain iterables without materialising them"),
    ("peekable", "wrap an iterator so its next item can be peeked"),
    ("split_when", "split a stream at boundaries where a predicate is true"),
    ("group_consecutive", "group consecutive equal items into runs"),
    ("running_max", "yield the running maximum of a stream"),
    ("running_min", "yield the running minimum of a stream"),
    ("running_mean", "yield the running mean of a numeric stream"),
    ("dedupe_stream", "yield items skipping consecutive duplicates lazily"),
    ("enumerate_from", "enumerate an iterable starting at a given index"),
    ("tail", "yield the last n items of an iterable using a buffer"),
    ("nth_lazy", "consume an iterator up to the nth item without a list"),
    ("count_iter", "count the items in an iterable, consuming it"),
    ("exhaust", "consume an iterator for its side effects"),
    ("chunk_stream_bytes", "yield fixed-size byte chunks from a byte iterator"),
    ("merge_sorted", "merge several sorted iterables into one sorted stream"),
    ("unique_justseen", "yield unique items ignoring only adjacent repeats"),
    ("pluck", "yield a named attribute or key from each item"),
    ("side_effect", "yield items while calling a function on each"),
    ("take_last_while", "yield the maximal trailing run satisfying a predicate"),
    ("roundrobin_longest", "interleave iterables continuing until all are exhausted"),
    ("flatmap", "map a function returning iterables and flatten the result"),
]

MATHX: list[Item] = [
    ("hypot", "return the Euclidean norm of several components"),
    ("clamp_angle", "wrap an angle into the range -pi to pi"),
    ("deg_normalize", "normalise a degree value into 0 to 360"),
    ("factorial_iter", "compute a factorial iteratively for large n"),
    ("double_factorial", "compute the double factorial n!!"),
    ("catalan", "return the nth Catalan number"),
    ("bell_number", "return the nth Bell number"),
    ("stirling_second", "return the Stirling number of the second kind"),
    ("harmonic", "return the nth harmonic number"),
    ("logn", "return the logarithm of x in an arbitrary base"),
    ("nth_root", "return the real nth root of a number"),
    ("integer_sqrt", "return the integer square root of a non-negative integer"),
    ("is_perfect_square", "test whether an integer is a perfect square"),
    ("modpow", "compute modular exponentiation efficiently"),
    ("modinv", "compute the modular multiplicative inverse"),
    ("chinese_remainder", "solve a system of congruences via CRT"),
    ("continued_fraction", "return the continued-fraction terms of a rational"),
    ("rationalize", "approximate a float as a fraction within a tolerance"),
    ("sigmoid", "compute the logistic sigmoid of a value"),
    ("softmax", "compute the softmax of a numeric vector"),
    ("relu", "compute the rectified linear unit of a value"),
    ("gaussian_pdf", "evaluate the normal probability density function"),
    ("erf_approx", "approximate the error function"),
    ("polynomial_eval", "evaluate a polynomial at x using Horner's method"),
    ("polynomial_derivative", "return the coefficients of a polynomial's derivative"),
    ("newton_root", "find a root of a function via Newton's method"),
    ("bisection_root", "find a root of a function via bisection"),
    ("trapezoidal_integral", "integrate a function numerically via the trapezoid rule"),
    ("simpson_integral", "integrate a function numerically via Simpson's rule"),
    ("derivative_at", "estimate a numerical derivative at a point"),
]

MATRIX: list[Item] = [
    ("mat_zeros", "build a matrix of zeros with given dimensions"),
    ("mat_identity", "build an identity matrix of a given size"),
    ("mat_add", "add two matrices element-wise"),
    ("mat_sub", "subtract two matrices element-wise"),
    ("mat_scale", "multiply a matrix by a scalar"),
    ("mat_mul", "multiply two matrices"),
    ("mat_transpose", "transpose a matrix"),
    ("mat_trace", "return the trace of a square matrix"),
    ("mat_determinant", "return the determinant of a square matrix"),
    ("mat_minor", "return a matrix with a row and column removed"),
    ("mat_cofactor", "return the cofactor matrix"),
    ("mat_inverse", "return the inverse of a square matrix or raise if singular"),
    ("mat_row_echelon", "reduce a matrix to row echelon form"),
    ("mat_rank", "return the rank of a matrix"),
    ("mat_solve", "solve a linear system by Gaussian elimination"),
    ("mat_power", "raise a square matrix to an integer power"),
    ("dot", "return the dot product of two vectors"),
    ("cross", "return the cross product of two 3-vectors"),
    ("vec_norm", "return the Euclidean norm of a vector"),
    ("vec_normalize", "scale a vector to unit length"),
    ("vec_add", "add two vectors element-wise"),
    ("vec_sub", "subtract two vectors element-wise"),
    ("vec_scale", "multiply a vector by a scalar"),
    ("outer_product", "return the outer product of two vectors"),
    ("mat_flatten", "flatten a matrix into a single list row-major"),
    ("mat_reshape", "reshape a flat list into a matrix of given dimensions"),
    ("mat_is_symmetric", "test whether a square matrix equals its transpose"),
    ("mat_diagonal", "return the diagonal of a matrix as a list"),
]

STATS: list[Item] = [
    ("geometric_mean", "return the geometric mean of positive numbers"),
    ("harmonic_mean", "return the harmonic mean of positive numbers"),
    ("weighted_mean", "return the weighted mean of values and weights"),
    ("covariance", "return the sample covariance of two sequences"),
    ("correlation", "return the Pearson correlation of two sequences"),
    ("spearman", "return the Spearman rank correlation of two sequences"),
    ("z_scores", "return the z-scores of a sequence"),
    ("iqr", "return the interquartile range of a sequence"),
    ("quartiles", "return the three quartiles of a sequence"),
    ("range_span", "return the difference between max and min"),
    ("skewness", "return the sample skewness of a sequence"),
    ("kurtosis", "return the excess kurtosis of a sequence"),
    ("mad", "return the mean absolute deviation of a sequence"),
    ("coefficient_of_variation", "return the ratio of standard deviation to mean"),
    ("linear_regression", "fit a simple linear regression returning slope and intercept"),
    ("r_squared", "return the coefficient of determination of a fit"),
    ("standardize", "rescale a sequence to zero mean and unit variance"),
    ("min_max_scale", "rescale a sequence into the range 0 to 1"),
    ("histogram_counts", "bucket values into a histogram of counts"),
    ("cumulative_distribution", "return the empirical CDF points of a sequence"),
    ("entropy", "return the Shannon entropy of a probability distribution"),
    ("gini", "return the Gini coefficient of a distribution"),
    ("bootstrap_mean", "estimate a mean confidence interval via bootstrapping"),
    ("rolling_std", "return the rolling standard deviation over a window"),
    ("winsorize", "clip a sequence's extremes to given percentiles"),
    ("rank", "return the ranks of a sequence with average ties"),
]

NUMBERTHEORY: list[Item] = [
    ("euler_totient", "return Euler's totient of an integer"),
    ("mobius", "return the Mobius function value of an integer"),
    ("divisor_count", "return the number of divisors of an integer"),
    ("divisor_sum", "return the sum of divisors of an integer"),
    ("is_perfect_number", "test whether an integer equals the sum of its proper divisors"),
    ("is_abundant", "test whether an integer is abundant"),
    ("is_deficient", "test whether an integer is deficient"),
    ("is_coprime", "test whether two integers are coprime"),
    ("extended_gcd", "return gcd and Bezout coefficients of two integers"),
    ("jacobi_symbol", "compute the Jacobi symbol of two integers"),
    ("legendre_symbol", "compute the Legendre symbol for an odd prime"),
    ("miller_rabin", "test primality probabilistically with Miller-Rabin"),
    ("pollard_rho", "find a non-trivial factor via Pollard's rho"),
    ("next_prime", "return the next prime greater than n"),
    ("prev_prime", "return the largest prime less than n"),
    ("nth_prime", "return the nth prime number"),
    ("prime_pi", "return the count of primes up to n"),
    ("is_carmichael", "test whether an integer is a Carmichael number"),
    ("radical", "return the product of distinct prime factors of an integer"),
    ("digital_persistence", "return how many digit-sum steps reduce n to one digit"),
    ("collatz_steps", "return the number of Collatz steps to reach one"),
    ("is_happy_number", "test whether an integer is a happy number"),
    ("is_armstrong", "test whether an integer is an Armstrong number"),
    ("triangular_number", "return the nth triangular number"),
    ("is_triangular", "test whether an integer is triangular"),
    ("pentagonal_number", "return the nth pentagonal number"),
    ("farey_sequence", "return the Farey sequence of order n"),
    ("sum_of_two_squares", "return a representation of n as a sum of two squares or None"),
]

COMBINATORICS: list[Item] = [
    ("nth_permutation", "return the nth lexicographic permutation of a sequence"),
    ("permutation_index", "return the lexicographic index of a permutation"),
    ("nth_combination", "return the nth combination of a size from a sequence"),
    ("multinomial", "return the multinomial coefficient of a group of counts"),
    ("derangements", "return the number of derangements of n items"),
    ("partitions", "yield the integer partitions of n"),
    ("partition_count", "return the number of integer partitions of n"),
    ("set_partitions", "yield all partitions of a set into non-empty blocks"),
    ("combinations_with_replacement_count", "count multisets of a size from n options"),
    ("subsets_of_size", "yield all subsets of a given size"),
    ("gray_code_sequence", "yield the n-bit binary reflected Gray code"),
    ("balanced_parentheses", "yield all balanced parenthesis strings of n pairs"),
    ("cartesian_power", "yield the n-fold cartesian power of a set"),
    ("lexicographic_rank", "return the rank of a string among its anagrams"),
    ("de_bruijn", "return a de Bruijn sequence for an alphabet and order"),
    ("necklaces", "count distinct necklaces of beads under rotation"),
    ("stars_and_bars", "count ways to place k identical items into n bins"),
    ("bell_triangle", "return the Bell triangle up to a row"),
    ("integer_compositions", "yield the ordered compositions of n"),
    ("catalan_paths", "yield monotonic lattice paths that stay below the diagonal"),
]

PROBABILITY: list[Item] = [
    ("binomial_pmf", "evaluate the binomial probability mass function"),
    ("poisson_pmf", "evaluate the Poisson probability mass function"),
    ("geometric_pmf", "evaluate the geometric probability mass function"),
    ("normal_cdf", "evaluate the standard normal cumulative distribution"),
    ("normal_ppf", "evaluate the inverse standard normal CDF"),
    ("expected_value", "return the expected value of outcomes and probabilities"),
    ("bayes", "apply Bayes' theorem to update a prior with a likelihood"),
    ("odds_to_prob", "convert odds to a probability"),
    ("prob_to_odds", "convert a probability to odds"),
    ("birthday_probability", "return the probability of a shared birthday among n people"),
    ("combinations_probability", "compute the probability of drawing a hand from a deck"),
    ("markov_step", "advance a distribution one step through a transition matrix"),
    ("stationary_distribution", "estimate the stationary distribution of a Markov chain"),
    ("kl_divergence", "compute the Kullback-Leibler divergence of two distributions"),
    ("cross_entropy", "compute the cross entropy of two distributions"),
    ("sample_categorical", "sample an index from a categorical distribution"),
    ("monte_carlo_pi", "estimate pi by Monte Carlo sampling"),
    ("confidence_interval", "return a normal-approximation confidence interval for a mean"),
    ("chi_square_stat", "compute a chi-square statistic for observed and expected counts"),
    ("expected_runs", "return the expected number of runs in a binary sequence"),
]

REGEXUTIL: list[Item] = [
    ("extract_emails", "return all email addresses found in text"),
    ("extract_urls", "return all http and https URLs found in text"),
    ("extract_hashtags", "return all hashtags found in text"),
    ("extract_mentions", "return all @mentions found in text"),
    ("extract_numbers", "return all numeric literals found in text"),
    ("extract_ipv4", "return all IPv4 addresses found in text"),
    ("extract_dates", "return ISO-style dates found in text"),
    ("glob_to_regex", "compile a shell glob pattern into a regex"),
    ("escape_regex", "escape a string for literal use in a regex"),
    ("named_capture", "return a dict of named groups from a match"),
    ("replace_all", "replace all matches of a pattern using a function"),
    ("split_keep_delimiters", "split text on a pattern keeping the delimiters"),
    ("find_between", "return substrings found between two delimiters"),
    ("strip_punctuation", "remove punctuation characters from a string"),
    ("match_wildcards", "match a string against a pattern with star and question wildcards"),
    ("template_fill", "replace {name} placeholders in a string from a mapping"),
    ("count_pattern", "count non-overlapping matches of a pattern"),
    ("redact_pattern", "replace matches of a pattern with a redaction marker"),
]

MARKDOWN: list[Item] = [
    ("md_bold", "wrap text in markdown bold markers"),
    ("md_italic", "wrap text in markdown italic markers"),
    ("md_link", "build a markdown link from text and a URL"),
    ("md_image", "build a markdown image from alt text and a URL"),
    ("md_code", "wrap text in an inline code span"),
    ("md_code_block", "wrap text in a fenced code block with a language"),
    ("md_heading", "build a markdown heading of a given level"),
    ("md_list", "render items as a markdown bullet list"),
    ("md_numbered_list", "render items as a markdown numbered list"),
    ("md_table", "render headers and rows as a markdown table"),
    ("md_blockquote", "prefix each line of text with a blockquote marker"),
    ("md_task_list", "render items with done flags as a markdown task list"),
    ("md_strip", "remove markdown formatting leaving plain text"),
    ("md_to_slug", "turn a heading into a GitHub-style anchor slug"),
    ("extract_links", "return all markdown links as text and URL pairs"),
    ("extract_headings", "return the headings and their levels from markdown"),
    ("build_toc", "build a markdown table of contents from headings"),
    ("md_hr", "return a markdown horizontal rule"),
    ("md_footnote", "build a markdown footnote reference and definition"),
    ("wrap_markdown", "wrap markdown text to a width without breaking links"),
    ("md_escape", "escape characters with special meaning in markdown"),
    ("front_matter_dump", "render a mapping as YAML-ish front matter"),
]

CALENDAR: list[Item] = [
    ("easter_date", "return the date of Easter Sunday for a year"),
    ("nth_weekday_of_month", "return the date of the nth given weekday in a month"),
    ("last_weekday_of_month", "return the last given weekday of a month"),
    ("is_us_federal_holiday", "test whether a date is a US federal holiday"),
    ("weekday_name", "return the English weekday name for a date"),
    ("month_name", "return the English month name for a month number"),
    ("month_calendar", "return a month as weeks of day numbers"),
    ("days_until_weekend", "return the number of days until the next weekend"),
    ("next_business_day", "return the next weekday after a date"),
    ("previous_business_day", "return the previous weekday before a date"),
    ("iso_week_dates", "return the seven dates of an ISO week"),
    ("quarter_dates", "return the start and end dates of a quarter"),
    ("season_of", "return the meteorological season of a date"),
    ("zodiac_sign", "return the western zodiac sign for a date"),
    ("chinese_zodiac", "return the Chinese zodiac animal for a year"),
    ("age_next_birthday", "return the number of days until the next birthday"),
    ("weeks_in_year", "return the number of ISO weeks in a year"),
    ("workdays_in_month", "count the weekdays in a month"),
    ("date_range_overlap_days", "count the overlapping days of two date ranges"),
    ("nth_day_of_year", "return the date for the nth day of a year"),
    ("moon_phase", "estimate the moon phase name for a date"),
    ("julian_day", "return the Julian day number for a date"),
]

I18N: list[Item] = [
    ("plural_rule_en", "return one or other for an English plural given a count"),
    ("format_list", "join a list into an English phrase with 'and'"),
    ("format_ordinal_word", "return the English ordinal word for a small integer"),
    ("number_to_words_en", "spell a non-negative integer in English words"),
    ("group_digits", "group an integer's digits with a thousands separator"),
    ("format_percent", "format a fraction as a percentage string"),
    ("direction_of", "return ltr or rtl for a language code"),
    ("normalize_locale", "normalise a locale string like en_us to en-US"),
    ("language_name", "return the English name for a language code"),
    ("country_name", "return the English name for an ISO country code"),
    ("currency_symbol", "return the symbol for a currency code"),
    ("format_bytes_locale", "format a byte size with a locale decimal separator"),
    ("transliterate", "map accented characters to ASCII approximations"),
    ("detect_script", "guess the writing script of a string"),
    ("pad_bidi", "wrap text with bidirectional isolation markers"),
    ("format_phone_us", "format a ten-digit string as a US phone number"),
    ("spell_currency_en", "spell a money amount in English words"),
    ("relative_time_en", "describe a signed seconds delta in English"),
]

VECTORS3D: list[Item] = [
    ("v3_add", "add two 3-vectors"),
    ("v3_sub", "subtract two 3-vectors"),
    ("v3_scale", "scale a 3-vector by a scalar"),
    ("v3_dot", "return the dot product of two 3-vectors"),
    ("v3_cross", "return the cross product of two 3-vectors"),
    ("v3_length", "return the length of a 3-vector"),
    ("v3_normalize", "return a unit 3-vector"),
    ("v3_distance", "return the distance between two 3-points"),
    ("v3_angle", "return the angle between two 3-vectors"),
    ("v3_lerp", "linearly interpolate between two 3-vectors"),
    ("v3_reflect", "reflect a 3-vector about a normal"),
    ("v3_project", "project one 3-vector onto another"),
    ("quat_multiply", "multiply two quaternions"),
    ("quat_conjugate", "return the conjugate of a quaternion"),
    ("quat_normalize", "normalise a quaternion"),
    ("quat_from_axis_angle", "build a quaternion from an axis and angle"),
    ("quat_to_euler", "convert a quaternion to Euler angles"),
    ("euler_to_quat", "convert Euler angles to a quaternion"),
    ("v3_rotate_axis", "rotate a 3-vector about an axis by an angle"),
    ("v3_midpoint", "return the midpoint of two 3-points"),
    ("v3_clamp_length", "clamp a 3-vector to a maximum length"),
    ("v3_component_along", "return the scalar component of a vector along another"),
    ("triangle_normal", "return the normal of a triangle from three points"),
    ("barycentric", "return the barycentric coordinates of a point in a triangle"),
]

PHYSICS: list[Item] = [
    ("kinetic_energy", "compute kinetic energy from mass and velocity"),
    ("potential_energy", "compute gravitational potential energy"),
    ("momentum", "compute momentum from mass and velocity"),
    ("force", "compute force from mass and acceleration"),
    ("work_done", "compute work from force and displacement"),
    ("projectile_range", "compute the range of a projectile"),
    ("projectile_flight_time", "compute the flight time of a projectile"),
    ("free_fall_distance", "compute distance fallen under gravity in a time"),
    ("terminal_velocity", "estimate terminal velocity from drag parameters"),
    ("ohms_law_voltage", "compute voltage from current and resistance"),
    ("resistors_series", "sum resistances in series"),
    ("resistors_parallel", "combine resistances in parallel"),
    ("capacitors_series", "combine capacitances in series"),
    ("wavelength_from_frequency", "compute wavelength from frequency and wave speed"),
    ("doppler_shift", "compute the observed frequency under the Doppler effect"),
    ("escape_velocity", "compute escape velocity from mass and radius"),
    ("orbital_period", "compute an orbital period from radius and central mass"),
    ("centripetal_force", "compute centripetal force from mass, speed, and radius"),
    ("pressure", "compute pressure from force and area"),
    ("density", "compute density from mass and volume"),
]

COMPRESSION: list[Item] = [
    ("rle_bytes_encode", "run-length encode a bytes object"),
    ("rle_bytes_decode", "decode run-length encoded bytes"),
    ("delta_encode", "delta-encode a list of integers"),
    ("delta_decode", "reverse delta encoding of integers"),
    ("lz77_compress", "compress bytes with a simple LZ77 scheme"),
    ("lz77_decompress", "decompress simple LZ77 output"),
    ("bwt_transform", "apply the Burrows-Wheeler transform to bytes"),
    ("bwt_inverse", "invert the Burrows-Wheeler transform"),
    ("move_to_front_encode", "apply the move-to-front transform"),
    ("move_to_front_decode", "invert the move-to-front transform"),
    ("dictionary_pack", "replace repeated tokens with short dictionary codes"),
    ("dictionary_unpack", "expand dictionary-packed tokens"),
    ("varint_list_encode", "encode a list of integers as concatenated varints"),
    ("varint_list_decode", "decode concatenated varints into integers"),
]

IMAGEPPM: list[Item] = [
    ("ppm_new", "create a blank RGB pixel grid of a width and height"),
    ("ppm_set_pixel", "set a pixel's colour in a grid"),
    ("ppm_get_pixel", "read a pixel's colour from a grid"),
    ("ppm_fill", "fill an entire grid with a colour"),
    ("ppm_to_p3", "serialise a grid to ASCII PPM P3 text"),
    ("ppm_to_p6", "serialise a grid to binary PPM P6 bytes"),
    ("ppm_from_p3", "parse ASCII PPM P3 text into a grid"),
    ("draw_line", "draw a line on a grid using Bresenham's algorithm"),
    ("draw_rect", "draw a rectangle outline on a grid"),
    ("fill_rect", "fill a rectangle on a grid"),
    ("draw_circle", "draw a circle outline on a grid"),
    ("flood_fill", "flood fill a region of a grid from a seed pixel"),
    ("grayscale_image", "convert an image grid to grayscale"),
    ("invert_image", "invert the colours of an image grid"),
    ("flip_horizontal", "flip an image grid horizontally"),
    ("flip_vertical", "flip an image grid vertically"),
    ("rotate_image_90", "rotate an image grid ninety degrees"),
    ("crop_image", "crop a rectangular region from an image grid"),
    ("resize_nearest", "resize an image grid using nearest-neighbour sampling"),
    ("blend_images", "alpha-blend two equal-size image grids"),
]

SCHEDULING: list[Item] = [
    ("next_cron_time", "return the next datetime matching a cron expression"),
    ("cron_iter", "yield successive datetimes matching a cron expression"),
    ("rrule_daily", "yield daily occurrences between two dates"),
    ("rrule_weekly", "yield weekly occurrences on given weekdays"),
    ("rrule_monthly", "yield monthly occurrences on a day of month"),
    ("interval_schedule", "yield times separated by a fixed interval"),
    ("debounce_times", "collapse a burst of timestamps to the last per window"),
    ("merge_free_busy", "compute free slots given busy intervals in a day"),
    ("earliest_common_slot", "find the earliest slot free for several calendars"),
    ("round_robin_assign", "assign tasks to workers in round-robin order"),
    ("deadline_sort", "order tasks by an earliest-deadline-first rule"),
    ("slot_conflicts", "return pairs of overlapping scheduled slots"),
    ("recurring_next_n", "return the next n occurrences of a recurrence"),
    ("business_hours_between", "count business hours between two datetimes"),
    ("timeslot_grid", "build a grid of time slots for a day at an interval"),
    ("throttle_schedule", "spread n events evenly across a window"),
    ("backfill_missing", "list missed occurrences of a schedule since a time"),
    ("weekly_hours", "sum scheduled hours per weekday from intervals"),
]

STATEMACHINE: list[Item] = [
    ("StateMachine", "a state machine with states, transitions, and a current state"),
    ("add_transition", "register a transition between two states on an event"),
    ("can_transition", "test whether an event is valid from the current state"),
    ("fire_event", "apply an event advancing the machine or raising if invalid"),
    ("history_stack", "track visited states to support going back"),
    ("to_dot", "render a state machine as Graphviz dot text"),
    ("reachable_states", "return the states reachable from a start state"),
    ("dead_states", "return states with no outgoing transitions"),
    ("validate_machine", "check a machine for unreachable or dead states"),
    ("guard_transition", "attach a predicate that must hold for a transition"),
    ("on_enter_hooks", "register callbacks fired when entering a state"),
    ("minimize_dfa", "minimise a deterministic finite automaton"),
]

GRAPHX: list[Item] = [
    ("bellman_ford", "compute shortest paths allowing negative edges or detect a cycle"),
    ("floyd_warshall", "compute all-pairs shortest paths"),
    ("astar", "find a shortest path using A* with a heuristic"),
    ("mst_kruskal", "compute a minimum spanning tree via Kruskal"),
    ("mst_prim", "compute a minimum spanning tree via Prim"),
    ("tarjan_scc", "find strongly connected components via Tarjan"),
    ("kosaraju_scc", "find strongly connected components via Kosaraju"),
    ("articulation_points", "find articulation points of an undirected graph"),
    ("bridges", "find bridge edges of an undirected graph"),
    ("bipartite_check", "test whether a graph is bipartite and return a colouring"),
    ("max_flow_edmonds_karp", "compute maximum flow via Edmonds-Karp"),
    ("min_cut", "compute a minimum cut from a max-flow result"),
    ("hamiltonian_path", "search for a Hamiltonian path in a small graph"),
    ("eulerian_path", "return an Eulerian path if one exists"),
    ("graph_coloring_greedy", "colour a graph greedily returning colour classes"),
    ("pagerank", "compute PageRank scores over a directed graph"),
    ("betweenness_centrality", "compute betweenness centrality of nodes"),
    ("degree_centrality", "compute degree centrality of nodes"),
    ("shortest_cycle", "return the length of the shortest cycle in a graph"),
    ("transitive_closure", "compute the transitive closure of a directed graph"),
    ("topological_layers", "group DAG nodes into dependency layers"),
    ("graph_diameter", "return the longest shortest-path length in a graph"),
]

ML: list[Item] = [
    ("euclidean_knn", "classify a point by k nearest neighbours"),
    ("kmeans", "cluster points into k groups by Lloyd's algorithm"),
    ("kmeans_plusplus_init", "choose initial centroids with k-means++"),
    ("linear_fit_gd", "fit a line by gradient descent"),
    ("logistic_fit", "fit logistic regression by gradient descent"),
    ("standard_scaler", "fit and apply zero-mean unit-variance scaling"),
    ("min_max_scaler", "fit and apply min-max feature scaling"),
    ("train_test_split", "split data and labels into train and test sets"),
    ("accuracy_score", "compute classification accuracy"),
    ("precision_recall", "compute precision and recall for binary predictions"),
    ("f1_score", "compute the F1 score for binary predictions"),
    ("confusion_matrix", "compute a confusion matrix for predictions"),
    ("mean_squared_error", "compute the mean squared error of predictions"),
    ("mean_absolute_error", "compute the mean absolute error of predictions"),
    ("r2_score", "compute the coefficient of determination of predictions"),
    ("cosine_similarity", "compute the cosine similarity of two vectors"),
    ("one_hot_encode", "one-hot encode a list of categorical labels"),
    ("label_encode", "map categorical labels to integer codes"),
    ("naive_bayes_fit", "fit a Gaussian naive Bayes classifier"),
    ("pca_1d", "project data onto its first principal component"),
    ("sigmoid_predict", "predict probabilities from weights and features"),
    ("decision_stump", "fit a one-rule threshold classifier"),
    ("silhouette_score", "compute the silhouette score of a clustering"),
    ("normalize_rows", "scale each row of a matrix to unit norm"),
]

CHECKDIGIT: list[Item] = [
    ("upc_check_digit", "compute the UPC-A check digit"),
    ("ean13_check_digit", "compute the EAN-13 check digit"),
    ("isbn13_check_digit", "compute the ISBN-13 check digit"),
    ("verhoeff_checksum", "compute the Verhoeff checksum of a numeric string"),
    ("verhoeff_validate", "validate a numeric string with its Verhoeff digit"),
    ("damm_checksum", "compute the Damm checksum of a numeric string"),
    ("damm_validate", "validate a numeric string with its Damm digit"),
    ("iban_check_digits", "compute the two IBAN check digits"),
    ("routing_number_valid", "validate a US ABA routing number checksum"),
    ("imei_valid", "validate an IMEI via the Luhn algorithm"),
    ("vin_check_digit", "compute the check digit of a vehicle VIN"),
    ("nhs_number_valid", "validate a UK NHS number checksum"),
    ("cusip_check_digit", "compute the CUSIP check digit"),
    ("isin_valid", "validate an ISIN with its Luhn-based check digit"),
]

CATEGORIES: list[tuple[str, str, list[Item]]] = [
    ("Strings", "strings", STRINGS),
    ("Numbers", "numbers", NUMBERS),
    ("Dates and times", "datetimes", DATETIME),
    ("Collections", "collections", COLLECTIONS),
    ("Functional", "functional", FUNCTIONAL),
    ("Encoding", "encoding", ENCODING),
    ("Hashing and checksums", "hashing", HASHING),
    ("Validation", "validation", VALIDATION),
    ("Parsing", "parsing", PARSING),
    ("Data structures", "structures", DATASTRUCTURES),
    ("Algorithms", "algorithms", ALGORITHMS),
    ("Randomness and IDs", "randomness", RANDOMNESS),
    ("Text search", "textsearch", TEXTSEARCH),
    ("Files and paths", "files", FILES),
    ("URLs and networks", "net", NET),
    ("Colours", "colors", COLORS),
    ("Unit conversions", "units", UNITS),
    ("Geometry", "geometry", GEOMETRY),
    ("Finance", "finance", FINANCE),
    ("Configuration", "config", CONFIG),
    ("Resilience", "resilience", RESILIENCE),
    ("Command line", "cli", CLI),
    ("Web framework", "webframework", WEBFRAMEWORK),
    ("Observability", "observability", OBSERVABILITY),
    ("Serialisation", "serialization", SERIALIZATION),
    ("Security", "security", SECURITY),
    ("Bitwise", "bits", BITS),
    ("Iterators and streams", "streams", STREAMS),
    ("Advanced math", "mathx", MATHX),
    ("Linear algebra", "matrix", MATRIX),
    ("Statistics", "stats", STATS),
    ("Number theory", "numbertheory", NUMBERTHEORY),
    ("Combinatorics", "combinatorics", COMBINATORICS),
    ("Probability", "probability", PROBABILITY),
    ("Regex helpers", "regexutil", REGEXUTIL),
    ("Markdown", "markdown", MARKDOWN),
    ("Calendar", "calendars", CALENDAR),
    ("Internationalisation", "i18n", I18N),
    ("3D vectors", "vectors3d", VECTORS3D),
    ("Physics", "physics", PHYSICS),
    ("Compression", "compression", COMPRESSION),
    ("Image (PPM)", "imageppm", IMAGEPPM),
    ("Scheduling", "scheduling", SCHEDULING),
    ("State machines", "statemachine", STATEMACHINE),
    ("Advanced graphs", "graphx", GRAPHX),
    ("Machine learning", "ml", ML),
    ("Check digits", "checkdigit", CHECKDIGIT),
]


def _toolkit_task(module: str, name: str, spec: str) -> str:
    return (
        f"({module}) Implement `{name}` in app/toolkit/{module}.py: {spec}. "
        f"Add a pytest in tests/toolkit/test_{module}.py covering the documented "
        f"behaviour and at least one edge case, and export `{name}` from "
        f"app/toolkit/__init__.py."
    )


def _interleaved_tasks() -> list[str]:
    """Round-robin across categories so early runs build breadth, not depth."""
    tasks: list[str] = []
    longest = max(len(items) for _, _, items in CATEGORIES)
    for i in range(longest):
        for _label, module, items in CATEGORIES:
            if i < len(items):
                name, spec = items[i]
                tasks.append(_toolkit_task(module, name, spec))
    return tasks


def build_backlog() -> str:
    lines: list[str] = [
        "# Backlog",
        "",
        "autoforge works through this list top to bottom, one item per run. Each",
        "item is small enough to implement and test in a single commit. Open items",
        "are `- [ ]`; completed items become `- [x]`. Anyone can add, reorder, or",
        "rewrite items — and when the open count runs low the runtime appends more",
        "(see `builder/backlog_gen.py`), so this list never truly ends.",
        "",
        "This file is generated by `tools/gen_backlog.py` from a curated taxonomy;",
        "edit that script to change the seed roadmap in bulk.",
        "",
        "## Foundation — the URL-shortener service",
        "",
    ]
    lines.extend(f"- [ ] {task}" for task in FOUNDATION)
    lines.append("")
    lines.append("## Toolkit — a self-building standard library")
    lines.append("")
    lines.append(
        "Each task adds one small, independently tested utility. Tasks are "
        "interleaved across areas on purpose."
    )
    lines.append("")
    lines.extend(f"- [ ] {task}" for task in _interleaved_tasks())
    lines.append("")
    return "\n".join(lines)


def task_count() -> int:
    return len(FOUNDATION) + len(_interleaved_tasks())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate BACKLOG.md.")
    parser.add_argument("--count", action="store_true", help="print the task count and exit")
    parser.add_argument("--output", default="BACKLOG.md", help="where to write the backlog")
    args = parser.parse_args(argv)

    if args.count:
        print(task_count())
        return 0

    repo_root = Path(__file__).resolve().parent.parent
    output = repo_root / args.output
    output.write_text(build_backlog(), encoding="utf-8")
    print(f"wrote {task_count()} tasks to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
